---
services:
  qbittorrent:
    # image: lscr.io/linuxserver/qbittorrent:latest
    build:
      context: .
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    user: root
    privileged: true
    container_name: qbittorrent-wg
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
      - TORRENTING_PORT=6881
      - CLIENT_PRIVATE_KEY=<key-here>
      - SERVER_PUBKEY=<key-here>
      - ENDPOINT=<endpoint-here>
    volumes:
      - ~/Movies/qbittorrent/appdata:/config
      - ~/Movies/Videos:/downloads #optional
    ports:
      - 8080:8080
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped


